### ISSUE TITLE
Karpenter unable to handle pod affinity rules while the node is starting up

### ISSUE THREAD

**Issue by kant777** [aws/karpenter-core#270]
### Version

karpernter version: v0.27.1
eks k8's version: 1.25

### Expected Behavior

I want group of pods(size = 3) land on the same node. the number of groups can be 100 or more. 

### Actual Behavior

I set the affinity rules for every group of pods and k8's seem to schedule fine as long the node is completely provisioned and ready however during the launch of a node by karpenter the pods go to pending state and never get scheduled. It fails with the following error

```

Warning  FailedScheduling  2m4s (x4 over 2m30s)  default-scheduler  0/3 nodes are available: 1 Insufficient memory, 1 node(s) didn't match pod affinity rules, 2 Insufficient cpu. preemption: 0/3 nodes are available: 1 Preemption is not helpful for scheduling, 2 No preemption victims found for incoming pod.
  Warning  FailedScheduling  64s (x15 over 2m14s)  karpenter          (combined from similar events): Failed to schedule pod, incompatible with provisioner "default", key kubernetes.io/hostname, kubernetes.io/hostname DoesNotExist not in kubernetes.io/hostname In [hostname-placeholder-0129]
  
```

### Steps to Reproduce the Problem

set the affinity rules similar to the spec below for a group of pods, turn off consolidation and launch a set of pods until a new node is getting spun up. watch the pod carefully when the node is getting spun up. it will result in an error

```
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: groupId
                    operator: In
                    values:
                      - "{{ .GroupId }}"
              topologyKey: "kubernetes.io/hostname"
              
```          

### Resource Specs and Logs

```
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: chainId
                    operator: In
                    values:
                      - "{{ .ChainId }}"
              topologyKey: "kubernetes.io/hostname"
              
 ```
 
 here is my provisioner
 
 ```
 apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:

  providerRef:
    name: default
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
  - key: karpenter.k8s.aws/instance-generation
    operator: Gt
    values:
    - "2"
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values: [c5, r5]
  # Exclude small instance sizes
  - key: karpenter.k8s.aws/instance-size
    operator: NotIn
    values: [nano, micro, small, large]
  - key: "karpenter.k8s.aws/instance-cpu"
    operator: In
    values: ["16", "32"]
  
  kubeletConfiguration:
    maxPods: 96


  # If omitted, the feature is disabled and nodes will never expire.  If set to less time than it requires for a node
  # to become ready, the node may expire before any pods successfully start.
  ttlSecondsUntilExpired: 2592000 # 30 Days = 60 * 60 * 24 * 30 Seconds;

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  securityGroupSelector:
    karpenter.sh/discovery: "eks-cluster-1"
  subnetSelector:
    karpenter.sh/discovery: "eks-cluster-1"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        iops: 10000
        encrypted: true
        deleteOnTermination: true
        throughput: 125
```

Here is the error from describing one of the pending pods 

```

Warning  FailedScheduling  2m4s (x4 over 2m30s)  default-scheduler  0/3 nodes are available: 1 Insufficient memory, 1 node(s) didn't match pod affinity rules, 2 Insufficient cpu. preemption: 0/3 nodes are available: 1 Preemption is not helpful for scheduling, 2 No preemption victims found for incoming pod.
  Warning  FailedScheduling  64s (x15 over 2m14s)  karpenter          (combined from similar events): Failed to schedule pod, incompatible with provisioner "default", key kubernetes.io/hostname, kubernetes.io/hostname DoesNotExist not in kubernetes.io/hostname In [hostname-placeholder-0129]
  
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kant777** [comment]
```
2023-04-04T18:21:28.975Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "7131be2-dirty", "pods": 33}
2023-04-04T18:21:28.975Z	INFO	controller.provisioner	computed new machine(s) to fit pod(s)	{"commit": "7131be2-dirty", "machines": 1, "pods": 2}
2023-04-04T18:21:28.975Z	INFO	controller.provisioner	launching machine with 2 pods requesting {"cpu":"4155m","memory":"4216Mi","pods":"5"} from types c5.4xlarge, r5.4xlarge, r5.8xlarge	{"commit": "7131be2-dirty", "provisioner": "default"}
2023-04-04T18:21:29.036Z	DEBUG	controller.provisioner.cloudprovider	discovered kubernetes version	{"commit": "7131be2-dirty", "provisioner": "default", "kubernetes-version": "1.25"}
2023-04-04T18:21:29.076Z	DEBUG	controller.provisioner.cloudprovider	discovered new ami	{"commit": "7131be2-dirty", "provisioner": "default", "ami": "ami-0a3da8b47de1d87b8", "query": "/aws/service/eks/optimized-ami/1.25/amazon-linux-2/recommended/image_id"}
2023-04-04T18:21:32.017Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "7131be2-dirty", "provisioner": "default", "id": "i-03977264ff6381b65", "hostname": "ip-172-16-114-70.ec2.internal", "instance-type": "c5.4xlarge", "zone": "us-east-1b", "capacity-type": "on-demand"}
2023-04-04T18:21:37.573Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", key kubernetes.io/hostname, kubernetes.io/hostname DoesNotExist not in kubernetes.io/hostname In [hostname-placeholder-0069]	{"commit": "7131be2-dirty", "pod": "saga-kantchain-1680622524149559-1/chainlet-7cb4f48ccb-46f88"}
2023-04-04T18:21:37.573Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", key kubernetes.io/hostname, kubernetes.io/hostname DoesNotExist not in kubernetes.io/hostname In [hostname-placeholder-0070]	{"commit": "7131be2-dirty", "pod": "saga-kantchain-1680622288085200-1/blockscout"}
2023-04-04T18:21:37.573Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "default", key kubernetes.io/hostname, kubernetes.io/hostname DoesNotExist not in kubernetes.io/hostname In [hostname-placeholder-0071]
```

**Comment by jonathan-innis** [comment]
Can you share your full pod/deployment spec as well?

**Comment by kant777** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Name }}"
        chainId: "{{ .ChainId }}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "26660"
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: chainId
                    operator: In
                    values:
                      - "{{ .ChainId }}"
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: "{{ .Image }}"
          name: "{{ .Name }}"
          imagePullPolicy: Always
          env:
          - name: CHAINID
            value: "{{ .ChainId }}"
{{ range $key, $value := .EnvVars }}
          - name: {{ $key | ToUpper }}
            value: "{{ $value }}"
{{ end }}
{{ range $key, $value := .SpcVars }}
          - name: SPCPARAM_{{ $key | ToUpper }}
            value: "{{ $value }}"
{{ end }}
          ports:
            - containerPort: 9090
            - containerPort: 1317
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
          - name: "saga-{{ .Name }}-persistent-storage"
            mountPath: "/root/.sagaevmd"
      volumes:
      - name: "saga-{{ .Name }}-persistent-storage"
        persistentVolumeClaim:
          claimName: "saga-{{ .Name }}-pvc"
      restartPolicy: Always
```
