### ISSUE TITLE
Node not rolled - After pods are scheduled on it and crash the node.

### ISSUE THREAD

**Issue by tip-dteller** [aws/karpenter-core#771]
### Description

**Observed Behavior**:
Background:
Windows application deployed on Karpenter Windows Nodes - Ami family 2019, **OnDemand** nodes.
When the application becomes unresponsive and enters CrashLoopBackOff, its breaks containerd 1.6.18.
The given error is:
```
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open //./pipe/containerd-containerd: The system cannot find the file specified."
```
* Side note: AWS recently updated Windows containerd from 1.6.8 to 1.6.18. 

Why does it matter for this case and how its relevant to Karpenter?

The node was created and _**was functional, it was in "Ready"**_ state as noted by Karpenter and the Windows pods were successfully scheduled onto it. So far so good.
When the application unexpectedly broke containerd and subsequently kubelet, the node enters "NotReady" state.
During this cycle, 

At this point, the node is not deprovisioned and prompts this in the events:
```
karpenter  Cannot deprovision Node: Nominated for a pending pod
```

Summary of events:
1. Deploy Windows application
2. Application is in Pending mode.
3. Karpenter provisions a functional windows node.
4. Application loads and enters Running state (its functional).
5. Application breaks containerd after N time.
6. Node is unresponsive.
7. Karpenter cannot deprovision the node because Old pods terminated and New pods are Pending.

**Expected Behavior**:

Detect that the node is unresponsive and roll it (i.e create a replacement node).

**Reproduction Steps** (Please include YAML):
Provisioner:
```
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: windows-provisioner
spec:
  consolidation:
    enabled: false
  limits:
    resources:
      cpu: 200
  labels:
    app: workflow
  ttlSecondsAfterEmpty: 300
  taints:
    - key: "company.io/workflow"
      value: "true"
      effect: "NoSchedule"
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "m", "r"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4", "8", "16", "32", "48", "64"]
    - key: "karpenter.k8s.aws/instance-generation"
      operator: Gt
      values: ["4"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type" 
      operator: In
      values: ["on-demand"] 
    - key: kubernetes.io/os
      operator: In
      values: ["windows"]

  providerRef:
    name: windows
```

I cannot provide the windows application as it entails business logic.

-- I Couldnt anything in Karpenter documentation that states this is normal behavior and I hope for some clarity here.

**Versions**:
- Chart Version:  v0.31.0
- Kubernetes Version (`kubectl version`): Server Version: v1.24.17-eks-f8587cb, Client Version: v1.28.3

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
