### ISSUE TITLE
Error: Unknown capacity type "capacity-block"

### ISSUE THREAD

**Issue by Nuru** [aws/karpenter-core#806]
### Description

**Observed Behavior**:

Repeated error messages in Karpenter logs:

```
ERROR	controller.deprovisioning	Received unknown capacity type capacity-block for instance type p5.48xlarge	{"commit": "709030d"}
```

**Expected Behavior**:

All capacity types are understood, even if not necessarily supported for provisioning.

**Reproduction Steps** (Please include YAML):

Run Karpenter in region `us-east-2` (Ohio).

See AWS documentation [Work with Capacity Blocks](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/capacity-blocks-using.html) and [Java psuedo-enum](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/model/UsageClassType.html#CapacityBlock).

See also

```
$ aws ec2 describe-instance-types --instance-types p5.48xlarge --query 'InstanceTypes[*].SupportedUsageClasses'
[
    [
        "capacity-block",
        "on-demand",
        "spot"
    ]
]
```

**Versions**:
- Chart Version: 0.31.2
- Kubernetes Version (`kubectl version`): 1.24.17

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
This should be fixed in the latest release (v0.32.1) with this PR fix: https://github.com/aws/karpenter/pull/4991

**Comment by Nuru** [comment]
@jonathan-innis We are reluctant to upgrade to v0.32.0 because of the [warnings about the v1beta1 APIs](https://karpenter.sh/v0.32/upgrading/upgrade-guide/#upgrading-to-v0320). Could you please backport https://github.com/aws/karpenter/pull/4991 to v0.31.x?

**Comment by tzneal** [comment]
You can still use the the older APIs with v0.32.x, it supports both versions.  The aws/karpenter repo is for anything AWS specific, karpenter-core is for more general issues.

**Comment by Nuru** [comment]
@jonathan-innis @tzneal A naïve update from v0.31.2 to v0.32.1 (simply changing the chart version number) failed with the following error:

```
panic: parsing settings, invalid character 'm' looking for beginning of value

goroutine 1 [running]:
github.com/samber/lo.must({0x25adc00, 0xc0006f8320}, {0x0, 0x0, 0x0})
	github.com/samber/lo@v1.38.1/errors.go:53 +0x1e9
github.com/samber/lo.Must[...](...)
	github.com/samber/lo@v1.38.1/errors.go:65
github.com/aws/karpenter-core/pkg/operator/injection.WithSettingsOrDie({0x308db90, 0xc000681800}, {0x30af1d8, 0xc0000c7380}, {0xc000490aa0, 0x2, 0x1?})
	github.com/aws/karpenter-core@v0.32.1/pkg/operator/injection/injection.go:88 +0x1ba
github.com/aws/karpenter-core/pkg/operator.NewOperator()
	github.com/aws/karpenter-core@v0.32.1/pkg/operator/operator.go:112 +0x6aa
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:33 +0x25
```

I'm not asking you to help figure out the error, but I am asking again for you to backport the "capacity-type" fix (all of 3 lines added to one file) to v0.31.3 so we can get this error fixed and out of our logs without having to invest in the v0.32 upgrade right now.

**Comment by jonathan-innis** [comment]
> I'm not asking you to help figure out the error

Can you share the `karpenter-global-settings` ConfigMap that you have here? I'm surprised that you wouldn't experience an error on `v0.31.x` for the ConfigMap but you _would_ hit an error starting on minor version `v0.32.x`? 

> but I am asking again for you to backport the "capacity-type" fix

Could you ignoring the error from your logs for the time being? This error should be benign and won't cause any issues with Karpenter running. Realistically, this error is occurring across all versions of Karpenter (aside from the newest versions) just based on the way that the capacity type parsing code was written and we won't be able to backport the change across all versions where this error is occurring.

**Comment by Nuru** [comment]
> > I'm not asking you to help figure out the error
> 
> Can you share the `karpenter-global-settings` ConfigMap that you have here? I'm surprised that you wouldn't experience an error on `v0.31.x` for the ConfigMap but you _would_ hit an error starting on minor version `v0.32.x`?
> 

<details><summary>karpenter-global-settings (click to reveal)</summary>

This is a dump of the `karpenter-global-settings` ConfigMap, with some of the Kubernetes-managed fields (like `managedFields`) removed, and with sensitive values redacted.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-global-settings
  namespace: karpenter
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.31.2
    helm.sh/chart: karpenter-v0.31.2
  annotations:
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: karpenter
data:
  aws.assumeRoleARN: ''
  aws.assumeRoleDuration: 15m
  aws.clusterCABundle: ''
  aws.clusterEndpoint: https://REDACTED.gr7.us-east-2.eks.amazonaws.com
  aws.clusterName: REDACTED-eks-cluster
  aws.defaultInstanceProfile: REDACTED-eks-karpenter
  aws.enableENILimitedPodDensity: 'true'
  aws.enablePodENI: 'false'
  aws.interruptionQueueName: REDACTED-auto-karpenter
  aws.isolatedVPC: 'false'
  aws.tags: >-
    {"Environment":"ue2","Name":"REDACTED-auto-karpenter","Namespace":"example","Service":"karpenter","Stage":"auto","Team":"sre","Tenant":"test"}
  aws.vmMemoryOverheadPercent: '0.075'
  batchIdleDuration: 1s
  batchMaxDuration: 10s
  featureGates.driftEnabled: 'false'
```

</details>


> > but I am asking again for you to backport the "capacity-type" fix
> 
> Could you ignoring the error from your logs for the time being? This error should be benign and won't cause any issues with Karpenter running. Realistically, this error is occurring across all versions of Karpenter (aside from the newest versions) just based on the way that the capacity type parsing code was written and we won't be able to backport the change across all versions where this error is occurring.

I'm not asking you to backport it to _all_ versions, just the latest pre-v0.32 version, especially since the general recommendation is to update to v0.31.2+ first, before updating to v0.32.
